---
- hosts: all

  # strategy: ansible.builtin.debug
  strategy: ansible.builtin.free

  vars_files:
    - default.config.yml
    - dock.config.yml
    - homebrew.config.yml
    - iterm.config.yml
    - ohmyzsh.config.yml
    - ssh.config.yml
    - vscode.config.yml

  pre_tasks:
    - name: Install Xcode
      community.general.mas:
        id: 497799835
        state: present

  roles:
    - name: Configure Iterm2
      role: lwalley.iterm2
      tags: ["all", "iterm"]

    - name: Configure Oh My Zsh
      role: gantsign.oh-my-zsh
      tags: ["all", "ohmyzsh"]

    - name: Configure Homebrew
      role: gordian_jklapacz.mac.homebrew
      tags: ["all", "homebrew"]

    - name: Configure Dock
      role: fubarhouse.macdock
      tags: ["all", "dock"]

    - name: Configure SSH
      role: lwalley.ssh-keys
      tags: ["all", "ssh"]

  tasks:
    - name: Execute defaults tasks
      include_tasks: tasks/defaults.yml
      args:
        apply:
          tags: ["all", "defaults"]
      tags: ["all", "defaults"]
    - name: Execute OhMyZsh tasks
      include_tasks: tasks/ohmyzsh.yml
      tags: ["all", "ohmyzsh"]
    - name: Execute Git tasks
      include_tasks: tasks/git.yml
      args:
        apply:
          tags: ["all", "git"]
      tags: ["all", "git"]
    - name: Execute GPG tasks
      include_tasks: tasks/gpg.yml
      tags: ["all", "gpg_create", "gpg_delete"]
    # NOTE: only limited to extensions
    - name: Execute VS Code tasks
      include_tasks: tasks/vscode.yml
      args:
        apply:
          tags: ["all", "vscode"]
      tags: ["all", "vscode"]
    - name: Execute Neofetch tasks
      include_tasks: tasks/neofetch.yml
      tags: ["all", "neofetch"]
    - name: Execute zshrc tasks
      include_tasks: tasks/zshrc.yml
      tags: ["all", "zshrc"]
    - name: Execute p10k tasks
      include_tasks: tasks/p10k.yml
      tags: ["all", "p10k"]
