---
# https://github.com/kevinSuttle/macOS-Defaults/blob/master/.macos
# Apps defaults

- name: Make TextEdit default to plain text
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0

- name: Enable focus follows mouse for Terminal
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: FocusFollowsMouse
    type: boolean
    value: true

# Global defaults

- name: Automatically quit printer app once the print jobs complete
  community.general.osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: boolean
    value: true

- name: Disable the “Are you sure you want to open this application?” dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: boolean
    value: false

- name: Disable natural scrolling
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: int
    value: 0
    state: present

- name: Enable always show scroll bars
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "Always"
    state: present

- name: Require password immediately after sleep or screen saver begins
  community.general.osx_defaults:
    domain: "com.apple.screensaver"
    key: askForPassword
    type: int
    value: 1
    state: present

- name: Require password immediately after sleep or screen saver begins (2)
  community.general.osx_defaults:
    domain: "com.apple.screensaver"
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

- name:  Save screenshots to the desktop
  community.general.osx_defaults:
    domain: "com.apple.screencapture"
    key: location
    type: string
    value: "${HOME}/Desktop"
    state: present

- name:  Save screenshots in PNG format (other options BMP, GIF, JPG, PDF, TIFF)
  community.general.osx_defaults:
    domain: "com.apple.screencapture"
    key: type
    type: string
    value: "png"
    state: present

- name:  Disable shadow in screenshots
  community.general.osx_defaults:
    domain: "com.apple.screencapture"
    key: disable-shadow
    type: boolean
    value: true
    state: present

# Trackpad, mouse, keyboard, Bluetooth accessories, and input defaults

- name: Enable right click (1)
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
    state: present

- name: Enable right click (2)
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: int
    value: 0
    state: present

- name: Enable tap to click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1
    state: present

- name: Enable tap to click in login screen
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
    state: present

- name: Increase sound quality for Bluetooth headphones/headsets
  community.general.osx_defaults:
    domain: com.apple.BluetoothAudioAgent
    key: "Apple Bitpool Min (editable)"
    type: int
    value: 40
    state: present

- name: Disable press-and-hold for keys in favor of key repeat
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: boolean
    value: false

- name: Set a blazingly fast keyboard repeat rate (1)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
    state: present

- name: Set a blazingly fast keyboard repeat rate (2)
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 10
    state: present

- name: Set languages
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - "en-SE"
      - "it-SE"
    state: present

- name: Set locale
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_SE"
    state: present

- name: Set measurement units
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: "Centimeters"
    state: present

- name: Set metric units
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: boolean
    value: true

# - name: Disable language menu in the top right corner of the boot screen
#   community.general.osx_defaults:
#     domain: "/Library/Preferences/com.apple.loginwindow"
#     key: showInputMenu
#     type: boolean
#     value: false

# Menu bar defaults

- name: Enable battery percentage
  community.general.osx_defaults:
    domain: "~/Library/Preferences/ByHost/com.apple.controlcenter.plist"
    key: BatteryShowPercentage
    type: int
    value: 1
    state: present
  
- name: Enable Bluetooth icon in menu bar
  community.general.osx_defaults:
      domain: "~/Library/Preferences/ByHost/com.apple.controlcenter.plist"
      key: Bluetooth
      type: int
      value: 18
      state: present

- name: Enable now playing icon in menu bar
  community.general.osx_defaults:
    domain: "~/Library/Preferences/ByHost/com.apple.controlcenter.plist"
    key: NowPlaying
    type: int
    value: 18
    state: present

- name: Enable volume icon in menu bar
  community.general.osx_defaults:
    domain: "~/Library/Preferences/ByHost/com.apple.controlcenter.plist"
    key: Sound
    type: int
    value: 18
    state: present

# Finder defaults

- name: Show filename extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: boolean
    value: true

- name: Show icons for hard drives on the desktop
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowExternalHardDrivesOnDesktop
    type: boolean
    value: true

- name: Show icons for servers on the desktop
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowHardDrivesOnDesktop
    type: boolean
    value: true

- name: Show icons for mounted servers on the desktop
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowMountedServersOnDesktop
    type: boolean
    value: true

- name: Show icons for removable media on the desktop
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowRemovableMediaOnDesktop
    type: boolean
    value: true

- name: Show finder status bar
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowStatusBar
    type: boolean
    value: true

- name: Show finder path bar
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: ShowPathbar
    type: boolean
    value: true

- name: Display full POSIX path as Finder window title
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: _FXShowPosixPathInTitle
    type: boolean
    value: true

- name: Keep folders on top when sorting by name
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: _FXSortFoldersFirst
    type: boolean
    value: true

- name: When performing a search, search the current folder by default
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
    state: present

- name: Disable the warning when changing a file extension
  community.general.osx_defaults:
    domain: "com.apple.finder"
    key: FXEnableExtensionChangeWarning
    type: boolean
    value: false

- name: Enable spring loading for directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "com.apple.springing.enabled"
    type: boolean
    value: true

- name: Remove the spring loading delay for directories
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "com.apple.springing.delay"
    type: float
    value: 0
    state: present

- name: Don't create .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: boolean
    value: true

- name: Don't create .DS_Store files on USB volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: boolean
    value: true

- name: Enable AirDrop over ethernet
  community.general.osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: boolean
    value: true

- name: Enable AirDrop over ethernet
  community.general.osx_defaults:
    domain: org.gpgtools.common
    key: UseKeychain
    type: boolean
    value: true

# Dock defaults

- name: Disable Dock auto-hide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: boolean
    value: false

- name: Don’t show recent applications in Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: boolean
    value: false

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen
- name: Set top right hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 13
    state: present
- name: Set top right hot corner 2
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0
    state: present
- name: Set bottom left hot corner
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 5
    state: present
- name: Set bottom left hot corner 2
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0
    state: present

# Safari defaults

- name: Don’t send search queries to Apple
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: UniversalSearchEnabled
    type: boolean
    value: false
- name: Don’t send search queries to Apple 2
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: SuppressSearchSuggestions
    type: boolean
    value: true

- name: Show the full URL in the address bar
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: boolean
    value: true

- name: Enable Safari’s debug menu
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeInternalDebugMenu
    type: boolean
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: boolean
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari 2
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: boolean
    value: true
- name: Enable the Develop menu and the Web Inspector in Safari 3
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled"
    type: boolean
    value: true
- name: Add a context menu item for showing the Web Inspector in web views
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: boolean
    value: true

- name: Warn about fraudulent websites
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WarnAboutFraudulentWebsites
    type: boolean
    value: true

- name: Block pop-up windows
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitJavaScriptCanOpenWindowsAutomatically
    type: boolean
    value: false
- name: Block pop-up windows 2
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically"
    type: boolean
    value: false