---
# Default theme
# oh_my_zsh_theme: "powerlevel10k/powerlevel10k"

# Default plugins
# oh_my_zsh_plugins:
#   - git
#   - zsh-syntax-highlighting
#   - zsh-autosuggestions
#   - git-flow-completion
#   - k
#   - enhancd

# Whether to install by default for all specified users.
# May be overridden by `oh_my_zsh: install:` under each user.
oh_my_zsh_install: true

# Default update mode for Oh-My-Zsh
# accepted values are:
# disabled (default)
# auto
# reminder
oh_my_zsh_update_mode: auto

# Default update frequency in days. When the update mode is set to a value other
# than "disabled", this is the frequency (in days) to check for a new version.
# The value 0 will check every time a new shell session starts.
oh_my_zsh_update_frequency: 13

# Whether to write the ~/.zshrc file
# May be overridden by `oh_my_zsh: write_zshrc:` under each user.
oh_my_zsh_write_zshrc: false

# User configuration
# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
users:
  - username: "{{ lookup('env', 'USER') }}"
