---
ssh_keys_dir: "{{ ansible_env.HOME }}/.ssh"
ssh_keys_pairs:
  default:
    type: ed25519
    bits: 4096
    path: "{{ ssh_keys_dir }}/id_ed25519"
    email: "{{ email }}"
    password: "{{ email }}"
    github: 
      - {
        label: "SSH key from {{ ansible_hostname }}",
        token: "{{ github_token }}"
      }
    bitbucket: 
      - {}
ssh_keys_config:
  - host: "*"
    config:
      - [ "AddKeysToAgent", "yes" ]
      - [ "UseKeychain", "yes" ]
  - host: "Github"
    config:
      - [ "User", "git" ]
      - [ "HostName", "github.com" ]
      - [ "PreferredAuthentications", "publickey" ]
      - [ "IdentityFile", "~/.ssh/id_ed25519" ]
