---
vscode_extensions:
  - 1yib.nodejs-bundle
  - 1yib.svelte-bundle
  - 42crunch.vscode-openapi
  - 4ops.terraform
  - aaron-bond.better-comments
  - ardenivanov.svelte-intellisense
  - astro-build.astro-vscode
  - bierner.color-info
  - bierner.markdown-preview-github-styles
  - christian-kohler.npm-intellisense
  - darkriszty.markdown-table-prettify
  - davidanson.vscode-markdownlint
  - dbaeumer.vscode-eslint
  - denoland.vscode-deno
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - fivethree.vscode-svelte-snippets
  - fnando.linter
  - foxundermoon.shell-format
  - github.copilot
  - github.copilot-chat
  - github.vscode-github-actions
  - hashicorp.terraform
  - henriiik.vscode-sort
  - idleberg.openvpn
  - jock.svg
  - kakumei.ts-debug
  - leo-ls.fiori-xml-lint
  - matheusq94.tfs
  - mcright.auto-save
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-ceintl.vscode-language-pack-it
  - ms-kubernetes-tools.vscode-aks-tools
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.debugpy
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  - ms-vscode-remote.remote-containers
  - ms-vscode.azure-account
  - ms-vscode.makefile-tools
  - ms-vscode.vscode-typescript-next
  - mtxr.sqltools
  - mtxr.sqltools-driver-mysql
  - mtxr.sqltools-driver-pg
  - naumovs.color-highlight
  - postman.postman-for-vscode
  - rangav.vscode-thunder-client
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - run-at-scale.terraform-doc-snippets
  - rvest.vs-code-prettier-eslint
  - standard.vscode-standard
  - stateful.runme
  - streetsidesoftware.code-spell-checker
  - svelte.svelte-vscode
  - tim-koehler.helm-intellisense
  - usernamehw.errorlens
  - vscode-icons-team.vscode-icons
  - xabikos.javascriptsnippets
  - yatki.vscode-surround
  - yzhang.markdown-all-in-one
